DELETE FROM JSBABEL.PAGESTRINGS WHERE PAGEID NOT IN (SELECT ID FROM PAGES);
DELETE FROM JSBABEL.PAGELONGSTRINGS WHERE PAGEID NOT IN (SELECT ID FROM PAGES);
DELETE FROM JSBABEL.BASESTRINGS WHERE ID NOT IN (SELECT STRINGID FROM PAGESTRINGS);
DELETE FROM JSBABEL.TARGETSTRINGS WHERE BASEID NOT IN (SELECT STRINGID FROM PAGESTRINGS);
DELETE FROM JSBABEL.BASELONGSTRINGS WHERE ID NOT IN (SELECT STRINGID FROM PAGELONGSTRINGS);
DELETE FROM JSBABEL.TARGETLONGSTRINGS WHERE BASEID NOT IN (SELECT STRINGID FROM PAGELONGSTRINGS);