SELECT DISTINCT
    B.TYPE, B.TEXT, T.TEXT, B.PAGEID IS NOT NULL
FROM
    BASESTRINGS B
        INNER JOIN
    TARGETSTRINGS T ON T.BASEID = B.ID
    INNER JOIN PAGESTRINGS ON B.ID = PAGESTRINGS.STRINGID
    INNER JOIN PAGES ON PAGES.ID = PAGESTRINGS.PAGEID
WHERE PAGES.SITEID = 16 AND T.LOCALE = 'EN-US' AND PAGES.PAGE = 'PAGE3.HTM' AND (B.PAGEID =PAGES.ID OR B.PAGEID IS NULL)
UNION SELECT DISTINCT
    B.TYPE, B.TEXT, T.TEXT, B.PAGEID IS NOT NULL
FROM
    BASELONGSTRINGS B
        INNER JOIN
    TARGETLONGSTRINGS T ON T.BASEID = B.ID
    INNER JOIN PAGELONGSTRINGS ON B.ID = PAGELONGSTRINGS.STRINGID
    INNER JOIN PAGES ON PAGES.ID = PAGELONGSTRINGS.PAGEID
WHERE PAGES.SITEID = 16 AND T.LOCALE = 'EN-US' AND PAGES.PAGE = 'PAGE3.HTM' AND (B.PAGEID =PAGES.ID OR B.PAGEID IS NULL);

SELECT DISTINCT
    B.TEXT, B.PAGEID IS NOT NULL
FROM
    BASESTRINGS B
    INNER JOIN PAGESTRINGS ON B.ID = PAGESTRINGS.STRINGID
    INNER JOIN PAGES ON PAGES.ID = PAGESTRINGS.PAGEID
WHERE B.TYPE = 3 AND PAGES.SITEID = 11  AND PAGES.PAGE = 'test_1.html' AND (B.PAGEID =PAGES.ID OR B.PAGEID IS NULL)
UNION SELECT DISTINCT
    B.TEXT, B.PAGEID IS NOT NULL
FROM
    BASELONGSTRINGS B
    INNER JOIN PAGELONGSTRINGS ON B.ID = PAGELONGSTRINGS.STRINGID
    INNER JOIN PAGES ON PAGES.ID = PAGELONGSTRINGS.PAGEID
WHERE B.TYPE = 3 AND PAGES.SITEID = 11  AND PAGES.PAGE = 'test_1.html' AND (B.PAGEID =PAGES.ID OR B.PAGEID IS NULL);

SELECT 
    *
FROM
    JSBABEL.BASESTRINGS
WHERE
    SITEID = 11 AND ID NOT IN (SELECT 
            STRINGID
        FROM
            PAGESTRINGS
        WHERE
            PAGEID IN (SELECT 
                    ID
                FROM
                    PAGES
                WHERE
                    SITEID = 11)) 
UNION SELECT 
    *
FROM
    JSBABEL.BASELONGSTRINGS
WHERE
    SITEID = 11 AND ID NOT IN (SELECT 
            STRINGID
        FROM
            PAGELONGSTRINGS
        WHERE
            PAGEID IN (SELECT 
                    ID
                FROM
                    PAGES
                WHERE
                    SITEID = 11));